/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function House(props) {
  const { nodes, materials } = useGLTF('/housec.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial002.geometry}
        material={materials.Barrel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial.geometry}
        material={materials.Bench}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial003.geometry}
        material={materials.Cart}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial005.geometry}
        material={materials.Chapel}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial004.geometry}
        material={materials.House}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial001.geometry}
        material={materials.Logs}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.defaultMaterial006.geometry}
        material={materials.Walls}
      />
    </group>
  )
}

useGLTF.preload('/housec.glb')
